export const buttons = [
  { sign: '0', id: "zero", type: "digit" },
  { sign: '1', id: "one", type: "digit" },
  { sign: '2', id: "two", type: "digit" },
  { sign: '3', id: "three", type: "digit" },
  { sign: '4', id: "four", type: "digit" },
  { sign: '5', id: "five", type: "digit" },
  { sign: '6', id: "six", type: "digit" },
  { sign: '7', id: "seven", type: "digit" },
  { sign: '8', id: "eight", type: "digit" },
  { sign: '9', id: "nine", type: "digit" },
  { sign: '+', id: "add", type: "operator" },
  { sign: '-', id: "subtract", type: "operator" },
  { sign: '*', id: "multiply", type: "operator" },
  { sign: '/', id: "divide", type: "operator" },
  { sign: '=', id: "equals", type: "answer" },
  { sign: '.', id: "decimal", type: "decimal" },
  { sign: 'AC', id: "clear", type: "clear" },
];