export const buttons = [
  { sign: "0", id: "zero", type: "digit", key: "0" },
  { sign: "1", id: "one", type: "digit", key: "1" },
  { sign: "2", id: "two", type: "digit", key: "2" },
  { sign: "3", id: "three", type: "digit", key: "3" },
  { sign: "4", id: "four", type: "digit", key: "4" },
  { sign: "5", id: "five", type: "digit", key: "5" },
  { sign: "6", id: "six", type: "digit", key: "6" },
  { sign: "7", id: "seven", type: "digit", key: "7" },
  { sign: "8", id: "eight", type: "digit", key: "8" },
  { sign: "9", id: "nine", type: "digit", key: "9" },
  { sign: ".", id: "decimal", type: "decimal", key: "." },
  { sign: "+", id: "add", type: "operator", key: "+" },
  { sign: "-", id: "subtract", type: "operator", key: "-" },
  { sign: "*", id: "multiply", type: "operator", key: "*" },
  { sign: "/", id: "divide", type: "operator", key: "/" },
  { sign: "=", id: "equals", type: "equals", key: "Enter" },
  { sign: "AC", id: "clear", type: "clear", key: "Escape" },
];